### ISSUE TITLE
[Bug] navigation bar is in light color even in dark theme

### ISSUE THREAD

**Issue by OliverLew** [leonlatsch/Photok#101]
**Describe the bug**
The navigation bar does not change color according to the theme. It's white in dark theme.

**To Reproduce**
1. Go to settings
2. Change to dark theme
3. See the navigation bar is white

**Expected behavior**
The color of navigation bar matches the theme.

**Screenshots**
![Screenshot_20210314-160024](https://user-images.githubusercontent.com/12032219/111061608-382d5300-84df-11eb-8d0c-7efdecccd17d.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8
 - OS: hydrogen OS 11 (based on Android 11)
 - Version: 11

**Additional context**
Photok is latest 1.2.4 from fdroid.

It doesn't matter if the navigation bar is a bar like the screenshot, or classic three button style in old Android versions, it's always white.

**Comment by leonlatsch** [comment]
I already noticed that one time.

Should be easy to fix 👍

**Comment by leonlatsch** [comment]
Fixed in 1.3.0.

Nav bar now has the same color as the Background.
