### ISSUE TITLE
Secret Dialer code does not work

### ISSUE THREAD

**Issue by ruralTom** [leonlatsch/Photok#102]
**Describe the bug**
Set up a secret dialercode ##xxxx## and when entered into the dialer, it tries to verify the code with t mobile.

**To Reproduce**
1. Go to set a dialer code
2. Click on dialer and try to launch the app via the dialer
3. T mobile tries to verify the code

**Expected behavior**
My photon would launch

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Moto g5plus (potter)
 - OS: android 11

**Additional c

How so I at least recover from this? When I try to launch the app directly the phone dialer launches. I haven't tried to clear data as I am worried I'll lose my gallery.

**Comment by leonlatsch** [comment]
@ruralTom You described `Set up a secret dialercode ##xxxx##`

The pattern is: `*#*#xxxx#*#*`. Have you tried that?

**Comment by ruralTom** [comment]
This wasn't a software or hardware issue


It was a wetware issue. 

I *am* the bug. *forehead slap*

**Comment by ruralTom** [comment]
I am so sorry I wasted your time

**Comment by leonlatsch** [comment]
No problem. I may switch the font because this font is kind of not displaing the `*` well, as you can see:
![image](https://user-images.githubusercontent.com/50983026/111697950-85d6f200-8836-11eb-93a5-daa191d0a3a7.png)
