### ISSUE TITLE
[Bug] app crashes while importing multiple photos

### ISSUE THREAD

**Issue by sivasren** [leonlatsch/Photok#104]
Tried  to import around 400 photos through files app (com.google.android.documents.ui). Imported first 40-60 but then it crashed after I retried to import again it force closed again.
And secret launch code doesn't work.

I have S10e, One UI 3.1 Android 11. I didn't try on AOSP ROM if anyone has Samsung can you try import multiple photos?

**Comment by leonlatsch** [comment]
Unfortunately I am not able to test this atm.
Import has been tested with 2000 photos before. I beleve it belongs to an error with a specific photo.

**Comment by leonlatsch** [comment]
@sivasren Since I am not able to reproduce this, I will close this for now.

Feel free to reopen tough.
