### ISSUE TITLE
[Bug] Es kann jeweils nur eine Foto aus der Galerie übernommen werden

### ISSUE THREAD

**Issue by jdardel** [leonlatsch/Photok#105]
Nachdem der Import von mehreren Fotos aus der Galerie anfänglich funktionierte, kann jetzt nur noch jeweils eine Foto übernommen werden.
Evtl. trat der Fehler auf, nachdem ich die App versteckte. Diese Funktion habe ich aber wieder rückgängig gemacht.

**Comment by leonlatsch** [comment]
Hi,

erstmal: Ich würde dich bitten, falls es dir möglich ist, hier auf Englisch zu schreiben, damit andere Benutzer in Zukunft auch ihren Nutzen aus den Issues ziehen können.

Zu deinem Fehler, welches Verhalten tritt genau auf, wenn du versuchst mehrere Fotos zu importieren?

**Comment by comparesheriff** [comment]
@jdardel, please answer, even if the bug doesn't exist on your end any longer.
It would be important to document weird bugs, so they can be fixed (or have work-arounds documented as long as there is no fix possible)

**Comment by leonlatsch** [comment]
Since there is no answer, I will close this. Feel free to reopen
