### ISSUE TITLE
[Feature] *your feature goes here* if i select an image to hide then the image should dissappear from the gallery ....!!!! 

### ISSUE THREAD

**Issue by vishwatejaaverager** [leonlatsch/Photok#108]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by comparesheriff** [comment]
@vishwatejaaverager, please consider reworking your ticket. 

It is not really clear what the problem and the suggested solution is. 
_Tip: Use a short title (e.g. 'Don't show hidden image in gallery') and then explain in a few sentences what behaviour is lacking and what you would suggest instead._

From my understanding this is also already a suggested feature under #55 so please check if this already satisfies your feature needs

**Comment by leonlatsch** [comment]
Yes as @comparesheriff mentioned. It seems like #55 already documented this issue. If so please tell us.

**Comment by leonlatsch** [comment]
I will close this for now. If #55 is not what you mean, feel free to reopen :)
