### ISSUE TITLE
Not available on F-droid repo anymore?

### ISSUE THREAD

**Issue by hellyeahmfs** [leonlatsch/Photok#133]
Is this app going to available on izzyondroid repo only?
Or its just lagging behind in updates?

**Comment by leonlatsch** [comment]
Yes it is available: https://f-droid.org/en/packages/dev.leonlatsch.photok/

**Comment by hellyeahmfs** [comment]
But the latest version available on f-droid repo is 1.3.2.16 .

**Comment by leonlatsch** [comment]
Yes, whenever I release a new version via GitHub F-Droid gets notified and a maintainer has to check it before.

Since F-Droid does not have that many maintainers, this process can take a few weeks.

**Comment by hellyeahmfs** [comment]
Ok got it. 🙂

**Comment by leonlatsch** [comment]
@hellyeahmfs Funfact: F-Droid release was broken cause I moved the app versions to a different file 😄 
Contacted F-Droid maintainers and they fixed it.
