### ISSUE TITLE
[Bug] *App icon*

### ISSUE THREAD

**Issue by hellyeahmfs** [leonlatsch/Photok#143]
**Describe the bug**
The app icon is not showing completely filled. It is showing as a circle in white square.

**Screenshots**
![App icon on home screen](https://user-images.githubusercontent.com/88529066/129892989-70e71684-7a47-4807-a782-a884b5ff9316.png)
 ![App icon in Aurora Store](https://user-images.githubusercontent.com/88529066/129893128-f440ce91-c234-4da4-8f8d-e417cdb604eb.png)

**Additional context**
Not a necessary issue but it looks cool in Play store version. If you have enough time please resolve this 😅 

Thanks for the app :-)

**Comment by leonlatsch** [comment]
Hm, interesting. Currently the app only has a round icon. Maybe I should add a normal version

**Comment by hellyeahmfs** [comment]
Yeah the app icon should be in square shape.
