### ISSUE TITLE
Export not working properly

### ISSUE THREAD

**Issue by jerryn70** [leonlatsch/Photok#160]
I have 2199 files in photok gallery both images and videos . When I select all files and try to export it to the gallery only 799 images is exported

**Comment by leonlatsch** [comment]
If you select all, are really all of them selected?

If not, this could be a bug related to paging.

**Comment by jerryn70** [comment]
@leonlatsch all files are selected. I scrolled through all the files and confirmed.

**Comment by leonlatsch** [comment]
@jerryn70 is the exporting dialog displaying the right amount of photos?

Eg: Exporting: 1/2199

Or is it displaying: 1/799

**Comment by leonlatsch** [comment]
@jerryn70 the configured max for photos loaded at once is 800.

This would match pretty well 🤔

**Comment by jerryn70** [comment]
@leonlatsch 1/799

**Comment by leonlatsch** [comment]
@jerryn70 Well, ok.

I will Label this a bug and fix it once I find the time.

As a workaround:

- Select all
- export
- Scroll down
- Export again

This should work, I guess.

**Comment by jerryn70** [comment]
@leonlatsch i tried this but it  creates too many duplicate file exports.

**Comment by jerryn70** [comment]
@leonlatsch Another export error in the latest fdroid version. It shows finished but nothing is exported to the gallery.

![](https://i.imgur.com/ihPCyWo.jpg)

**Comment by leonlatsch** [comment]
The Problem
----

The multi selection is index based.

When selecting all, the item count is used for add all items. The item count also includes all placeholders, added by paging.

So the placeholders are selected, but no item lays behind it. Therefore they cannot be used.

**Comment by leonlatsch** [comment]
We may think about dropping paging, since the data that is currently loaded paged, is not big.
Loading the thumbnails happens in the ViewHolder's onBind anyway.

**Comment by SeleDreams** [comment]
This issue is still present for me

**Comment by leonlatsch** [comment]
I know, sorry about that.

This is a complex issue wich involves rewriting a bug chunk of logic.
