### ISSUE TITLE
[Feature] Add Photo/Video Editor

### ISSUE THREAD

**Issue by uuuussseer** [leonlatsch/Photok#161]
**Is your feature request related to a problem? Please describe.**
When I import a image/video into the app, I may want to edit it after. As of now, I can't. It would be nice to have the ability to do this. Once issue #87 (take encrypted photo) is implemented, it would be useful to have the image/video completely stay in the app. This would leave no forensically recoverable data on the device.

**Describe the solution you'd like**
A simple photo/video editor.

**Describe alternatives you've considered**
Taking the image/video out of the app and editing it, then putting it back in the app. This is a hassle, and as mentioned above once encrypted photo/video taking is implemented, it would be nice to have no forensically recoverable data on the device, and to keep the image/video completely in the app.

**Additional context**
The Gallery Go editor can be used for inspiration as it is simple, yet powerful. 
Simple Mobile Tools also has a application called [Simple Gallery](https://github.com/SimpleMobileTools/Simple-Gallery) which has a nice simple editor.
Also, I have no idea if there is a possibility of a video editor, if it is not possible that is fine. 
Thanks for making this wonderful app!

**Comment by leonlatsch** [comment]
Im sorry, but this is out of scope for Photok right now.
