### ISSUE TITLE
[Bug] Wrong video deleted

### ISSUE THREAD

**Issue by alxgnon** [leonlatsch/Photok#163]
**Describe the bug**
In some circumstances, when deleting a video in a list, the previous video is deleted instead.

**To Reproduce**
I have not been able to reproduce this bug. It has happened to me twice. I will continue testing to see if I can figure out a method to reproduce it.

**Expected behavior**
The selected video should be deleted but instead the previous video was deleted.

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Lineage 18.1
 - Photok Version: 1.3.4

**Additional context**
I was scrolling through videos and deleting some of them. I deleted a first video, and it worked fine. Then, a bit later, I deleted another video, and it actually deleted the one before it, leaving the one I wanted to delete intact, and removing a video I actually wanted to keep.

I have tried to reproduce this with sample videos for testing, and I have not been successful, yet.

I am still reporting this bug because I have observed this happening twice before my very own eyes and I think it's important to signal this to the developer. However, I understand that it makes it hard to debug since I haven't found a way to reproduce it, yet. So I hope to continue testing this to see what causes it.

**Comment by leonlatsch** [comment]
Would very likely be fixed with #160. So closing this one :)
