### ISSUE TITLE
[Bug] Not able to restore backups on another device

### ISSUE THREAD

**Issue by mubaid** [leonlatsch/Photok#165]
**Describe the bug**
The backups taken on old device are not being able to restore on new device. Total backup size is ~1.2GB. Photok Password is same on both devices.

**To Reproduce**
1. Go to Photok and Create a backup
2. Copy the backup file to new device
3. Start Photok on new device, set the password and restore backup
4. Fails on "Validating Backup" - the app crashes

**Expected behavior**
Backup taken on any device should be restored on new device (since the password used on both devices is the same)

**Smartphone (please complete the following information):**
 - Old Device: Oppo K1, Android 9, ColorOS 6.0.1
 - New Device: Poco F3, 6GB RAM, Android 11, Miui 12.5.18 stable
 - App version (on both devices) : Latest playstore, 1.3.4

**Additional Info**
Both the phones are not rooted, do not have Magisk or Vanced installed.
Password used is same on both the devices.
Backup file, restore file hash matches - backup file generated on source is same file used to restore
Backup zip file opens on windows laptop (so the backup isn't corrupted).

**Comment by leonlatsch** [comment]
Unfortunately, I wan't able to reproduce this. So this will be closed for now :/

If this is still bothering you, feel free to reopen.
