### ISSUE TITLE
[bug] cant launch hidden app

### ISSUE THREAD

**Issue by pruebando** [leonlatsch/Photok#166]
Cant Launch hidden app

i hid the app and the launch code does nothing when i put it, i dont know why but it just doesnt work just deleted the text of the marker and just it

On a xiaomi redmi 9 pro f droid version 1.3.2

**Comment by pruebando** [comment]
i even tried if i forgot the password and installed an app to see the dialer codes and it doesnt even appear

**Comment by pruebando** [comment]
Hi it fixed randomly if it happens to you just wait a lot and try to share pics to the app

**Comment by pruebando** [comment]
ok so you need to share one pic to the app, then enter and disable hide app

**Comment by leonlatsch** [comment]
Yes, this is known on some devices and can get bypassed with this "hack"
See this #141
