### ISSUE TITLE
[Bug] Apps keep crashing after login

### ISSUE THREAD

**Issue by Dovakiin0** [leonlatsch/Photok#167]
**Describe the bug**
Cannot access the app as it keeps crashing right after login

**To Reproduce**
1. Go to login
2. Enter valid password
3. Crashes

**Expected behavior**
Should access the app when entered valid password

**Additional context**
I imported all photos and videos without second thought now the app wont even start. Can you help with this. Atleast can you tell where the photos and vids are stored for now?

**Comment by jthvai** [comment]
@Dovakiin0 I assume you closed this issue because you found and fixed the problem? If so, could you please elaborate on your solution - I am having the exact same problem :)
