### ISSUE TITLE
Question about Privacy Policy

### ISSUE THREAD

**Issue by johndoe432** [leonlatsch/Photok#168]
The Privacy Policy of Photok says the following:
> I want to inform you that whenever you use my Service, in a case of an error in the app I collect data and information (through third party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing my Service, the time and date of your use of the Service, and other statistics. 

How can the app collect the mentioned data, if it do not have access to the internet?

**Comment by leonlatsch** [comment]
This data is not collected by the app itself.

If you use the Google Play Version, the Google Play Services collect error logs, etc.

**Comment by johndoe432** [comment]
> This data is not collected by the app itself.
> 
> If you use the Google Play Version, the Google Play Services collect error logs, etc.

Oh, I understand, thanks for your answer and thanks for creating such a useful app 😄
