### ISSUE TITLE
[Bug] 1.3.5 is not on F-Droid

### ISSUE THREAD

**Issue by yephny** [leonlatsch/Photok#175]
Although it shows up in Izzy's, version 1.3.5 is not on the official F-Droid repo, even after 2 repository updates following the release of this version. Is there something wrong with the F-Droid configuration on your end for the new version?

**Comment by leonlatsch** [comment]
In the past, Fdroid took multiple days to update (for example last version took 11 days). 

I'll keep waiting for f-droid for a while and reopen this in case its taking longer than eg. 14 days.
