### ISSUE TITLE
SECURITY: Fundamental wrong design and choice of primitives

### ISSUE THREAD

**Issue by qua3k** [leonlatsch/Photok#177]
This application suffers from numerous fundamental problems in its cryptography, beginning with key derivation and ending with IV reuse.

The key derivation is broken. SHA-256 is a cryptographic hash function, not a purpose built KDF. It's meant to be extremely fast and as such, attackers can just make massive rainbow tables for the key. Modern KDFs (such as Argon2) are memory-hard and resistant against brute-force search.

Furthermore, you use the password (literally the plain password) as the IV. Encrypting different data with the same IV utterly breaks any protection you may have had, as well as leaking the authentication key. Even CBC mode (an unauthenticated mode) is more resistant to IV reuse.

This is from 10 minutes of looking at source code, so there may be other issues I haven't found. However, I can't recommend this app to anyone looking for any semblance of security when the encryption is so fundamentally broken. 

Please don't take the wrong way if I come across too harsh, I have just seen too much broken cryptography

**Comment by leonlatsch** [comment]
Thank you for this detailed critique.

Since I am no security expert, I just implemented what I new worked (back then when I started developing the app).

This issue is defenetly an inspiration to maybe rethink the cryptography part in this app and implement/migrate to a more safer algorithm.

Leave some resources or more detailed explainations for me would be very kind.

**Comment by leonlatsch** [comment]
The idea behind using a hash key for encrypting was that I don't need to save anything on device and the encryption key can just be hold in memory. But I understand that its not desiigned for that.

Although, for the fingerprint feature I may need to save the key on device anyways, so I will look into that.

**Comment by leonlatsch** [comment]
Since there seems to be no more conversation on this topic. 

Please note that your complaints about it, have been taken into account.
