### ISSUE TITLE
Updated ru (Russian) translation

### ISSUE THREAD

**Issue by chel1k** [leonlatsch/Photok#178]
I have translated your application into `ru` (*Russian*). Here is the xml:

<?xml version="1.0" encoding="utf-8"?>

<resources>

    
    <string name="app_name">Photok</string>
    <string name="common_copyright_notice">Copyright \\00A9 2020–2021 Leon Latsch</string>
    <string name="common_slash">/</string>
    <string name="common_percent">%</string>
    <string name="common_pipe">|</string>
    <string name="common_loading">Загрузка ...</string>
    <string name="common_password">Пароль</string>
    <string name="common_delete">Удалить</string>
    <string name="common_export">Экспортировать</string>
    <string name="common_error">Произошла ошибка. Пожалуйста, попробуйте еще раз.</string>
    <string name="common_yes">Да</string>
    <string name="common_no">Нет</string>
    <string name="common_ok">ОК</string>
    <string name="common_are_you_sure">Вы уверены?</string>
    <string name="common_bullet">•</string>

    >
    <string name="import_importing">Импортирование файла(ов)</string>
    <string name="import_permission_rationale">Photok необходимо получить доступ к вашему хранилищу, чтобы импортировать файлы.</string>
    <string name="import_sharted_question">Вы хотите импортировать %1$d файл(ов)?</string>

    
    <string name="setup_create_your_password">Создайте свой пароль</string>
    <string name="setup_enter_password">Введите пароль</string>
    <string name="setup_confirm_password">Подтвердите свой пароль</string>
    <string name="setup_password_strength_label">Надежность пароля:</string>
    <string name="setup_button">Создать</string>
    <string name="setup_password_strength_weak">Слабый</string>
    <string name="setup_password_strength_moderate">Умеренный</string>
    <string name="setup_password_strength_strong">Сильный</string>
    <string name="setup_password_match_warning">\\26A0 Пароли не совпадают</string>
    <string name="setupSetup">Установка</string>

    
    <string name="unlock_title">Разблокируйте свой сейф</string>
    <string name="unlock_enter_password">Введите пароль</string>
    <string name="unlock_button">Разблокировать</string>
    <string name="unlock_wrong_password">\\26A0 Неверный пароль</string>

    
    <string name="gallery_placeholder">В вашем сейфе нет файлов</string>
    <string name="gallery_all_photos_label">Все файлы</string>

    
    <string name="import_menu_title">Импорт</string>
    <string name="import_menu_photos">Фотографии</string>
    <string name="import_menu_videos">Видео</string>
    <string name="import_menu_backup">Резервное копирование</string>
    <string name="import_menu_hint">Добавьте медиаэлементы в Photok...</string>

    
    <string name="process_close">Закрыть</string>
    <string name="process_abort">Отмена</string>
    <string name="process_finished">Законченный</string>
    <string name="process_initialize">Подготовка...</string>
    <string name="process_aborted">Прервано</string>
    <string name="process_failures_occurred">\\26A0 Некоторые элементы не удалось обработать</string>

    
    <string name="view_photo_detail_title">Подробности</string>
    <string name="view_photo_detail_file_name_label">Имя файла:</string>
    <string name="view_photo_detail_import_at_label">Импортировано в:</string>
    <string name="view_photo_detail_file_type_label">Тип файла:</string>
    <string name="view_photo_detail_size_label">Размер файла:</string>

    
    <string name="menu_main_lock">Блокировка</string>
    <string name="menu_main_settings">Настройки</string>

    
    <string name="menu_ms_select_all">Выбрать все</string>
    <string name="menu_ms_delete">Удалить</string>
    <string name="menu_ms_export">Экспортировать</string>

    
    <string name="delete_are_you_sure">Вы уверены, что хотите <b >удалить</b> %1$d файл(ов)?</string>
    <string name="delete_are_you_sure_this">Вы уверены, что хотите <b >удалить</b> эти файлы?</string>
    <string name="delete_deleting">Удаление файла(ов)...</string>

    
    <string name="export_are_you_sure">Вы уверены, что хотите <b >экспортировать</b> %1$d файл(ы) обратно в вашу галерею?</string>
    <string name="export_are_you_sure_this">Вы уверены, что хотите <b >экспортировать</b> этот файл в свою галерею?</string>
    <string name="export_exporting">Экспорт файла(ов)...</string>
    <string name="export_permission_rationale">Photok необходим доступ к вашему хранилищу, чтобы экспортировать файлы.</string>
    <string name="export_finished">Экспортировано</string>

    
    <string name="about_version">Версия:</string>
    <string name="about_developed_by">Разработано:</string>
    <string name="about_website_label">leonlatsch.dev</string>
    <string name="about_website_url">https://leonlatsch.dev</string>
    <string name="about_third_party">Программное обеспечение сторонних производителей</string>
    <string name="about_privacy_policy">Политика конфиденциальности</string>
    <string name="about_privacy_policy_url">https://leonlatsch.dev/photok_privacy_policy</string>
    <string name="about_menu_news">Новости</string>

    
    <string name="settings_title">Настройки</string>

    <string name="settings_category_app">Приложение</string>
    <string name="settings_app_design_title">Дизайн</string>
    <string name="settings_app_design_system_default">По умолчанию системы</string>
    <string name="settings_app_design_system_light">Светлый</string>
    <string name="settings_app_design_system_dark">Темный</string>

    <string name="settings_category_gallery">Галерея</string>
    <string name="settings_gallery_auto_fullscreen_title">Автоматический полный экран</string>
    <string name="settings_gallery_auto_fullscreen_summary">Переход в полноэкранный режим при открытии файла</string>

    <string name="settings_category_security">Безопасность</string>
    <string name="settings_security_allow_screenshots_title">Разрешить скриншоты</string>
    <string name="settings_security_allow_screenshots_summary">Позволяет делать снимки экрана. Требуется перезагрузка.</string>
    <string name="settings_security_change_password_title">Изменить пароль</string>
    <string name="settings_security_change_password_summary">Изменить пароль</string>
    <string name="settings_security_timeout_title">Таймаут автоматической блокировки</string>
    <string name="settings_security_timeout_summary">Автоматическая блокировка через заданное время в фоновом режиме</string>
    <string name="settings_security_timeout_immediately">Немедленно</string>
    <string name="settings_security_timeout_one_minute">1 минута</string>
    <string name="settings_security_timeout_two_minute">2 Минут</string>
    <string name="settings_security_timeout_five_minute">5 минут</string>
    <string name="settings_security_timeout_ten_minute">10 Минут</string>
    <string name="settings_security_timeout_never">Никогда</string>
    <string name="settings_security_launch_code_title">Секретный код запуска</string>
    <string name="settings_security_launch_code_summary">Секретный код для запуска Photok из телефонного номеронабирателя.</string>
    <string name="settings_security_launch_code_message">Введите *#**#[ваш код]#*#* в телефонном номеронабирателе, чтобы запустить Photok.</string>
    <string name="settings_security_launch_code_prefix">*#*#</string>
    <string name="settings_security_launch_code_suffix">#*#*</string>
    <string name="settings_security_hide_app_title">Скрыть приложение</string>
    <string name="settings_security_hide_app_summary">Скрыть значок приложения из ящика приложений.</string>

    <string name="settings_category_advanced">Расширенный</string>
    <string name="settings_category_advanced_summary">Используйте осторожно</string>
    <string name="settings_advanced_reset_title">Сброс в безопасное состояние</string>
    <string name="settings_advanced_reset_summary">Очистка данных и сброс пароля</string>
    <string name="settings_advanced_reset_confirmation">Вы действительно хотите сбросить настройки своего сейфа? Все данные будут потеряны!</string>
    <string name="settings_advanced_backup_title">Резервное копирование</string>
    <string name="settings_advanced_backup_summary">Создайте резервную копию своего сейфа</string>

    <string name="settings_other_title">Другое</string>
    <string name="settings_other_feedback_title">Обратная связь</string>
    <string name="settings_other_feedback_summary">Отправьте мне письмо с отзывом</string>
    <string name="settings_other_feedback_mail_subject">Обратная связь с Photok</string>
    <string name="settings_other_feedback_mail_body">Написать отзыв о Photok :)</string>
    <string name="settings_other_feedback_mail_emailaddress">dev.leonlatsch@gmail.com</string>
    <string name="settings_other_sourcecode_title">Исходный код</string>
    <string name="settings_other_sourcecode_summary">Внести вклад в Photok</string>
    <string name="settings_other_sourcecode_url">https://github.com/leonlatsch/Photok</string>
    <string name="settings_other_credits_title">Кредиты</string>
    <string name="settings_other_credits_summary">Участники и кредиты</string>
    <string name="settings_other_about_title">About</string>
    <string name="settings_other_about_summary">Информация о Photok</string>

    
    <string name="credits_contributors_title">Соавторы</string>
    <string name="credits_contributors_hint">Посетите Photok на GitHub, чтобы увидеть всех соавторов</string>
    <string name="credits_icons_title">Иконки</string>

    
    <string name="change_password_title">Сменить пароль</string>
    <string name="change_password_old_password">Старый пароль</string>
    <string name="change_password_new_password">Новый пароль</string>
    <string name="change_password_check">Проверить</string>
    <string name="change_password_enter_new_password">Введите новый пароль</string>
    <string name="change_password_confirm_new_password">Подтвердите новый пароль</string>
    <string name="change_password_button">Сменить пароль</string>
    <string name="change_password_confirm_message">Рекомендуется резервное копирование!<br ></br> Изменение пароля требует повторного шифрования всех ваших файлов! Вы хотите продолжить?</string>
    <string name="change_password_reencrypting">Повторное шифрование файла(ов)...</string>

    
    <string name="hide_app_title_hide">Скрыть Photok</string>
    <string name="hide_app_title_show">Показать Photok</string>
    <string name="hide_app_status_label">В настоящее время Photok:</string>
    <string name="hide_app_status_visible">ВИДИМЫЙ</string>
    <string name="hide_app_status_hidden">СКРЫТЫЙ</string>
    <string name="hide_app_app_name_stealth">Телефон</string>
    <string name="hide_app_confirm_hide">Вы действительно хотите скрыть Photok?</string>
    <string name="hide_app_confirm_show">Вы хотите снова показать Photok?</string>
    <string name="hide_app_hint">После скрытия Photok можно запустить только с панели набора номера телефона, введя секретный код запуска.</string>
    <string name="hide_app_hint_current_code">Текущий стартовый код:</string>

    
    <string name="onboarding_next">Следующий</string>
    <string name="onboarding_finish">Финиш</string>
    <string name="onboarding_skip"><u >Пропустить</u></string>

    <string name="onboarding_slide1_title">Добро пожаловать в</string>
    <string name="onboarding_slide1_description">Безопасное место для ваших фотографий.</string>
    <string name="onboarding_slide2_title">Придумайте пароль</string>
    <string name="onboarding_slide2_description">Создайте надежный пароль. Ваш пароль используется для шифрования фотографий непосредственно на телефоне.</string>
    <string name="onboarding_slide3_title">Начать импорт</string>
    <string name="onboarding_slide3_description">Начните импортировать свои фотографии и храните их в безопасности от других.\n
 После этого вы сможете удалить их в своей галерее.</string>

    
    <string name="backup_processing_title">Создание резервной копии...</string>
    <string name="backup_restore_title">Восстановление резервной копии</string>
    <string name="backup_restore_validating">Проверка резервной копии...</string>
    <string name="backup_restore_details_created_at">Создан в:</string>
    <string name="backup_restore_details_photos_contained">Содержимое файлов:</string>
    <string name="backup_restore_details_compatible">Совместимость:</string>
    <string name="backup_restore_details_size">Размер:</string>
    <string name="backup_restore_button">Разблокировка и восстановление</string>
    <string name="backup_restore_invalid_file">\\26A0 Invalid File</string>
    <string name="backup_restore_processing">Восстановление резервной копии...</string>
    <string name="backup_unlock_title">Разблокировка резервной копии</string>

    
    <string name="news_new_in_title">Новое в</string>
    <string name="news_view_changelog">Посмотреть журнал изменений</string>
    <string name="news_changelog_url">https://github.com/leonlatsch/Photok/releases</string>

    <string name="news_title_1">Функция: Импорт видео</string>
    <string name="news_summary_1">Импорт видео в Photok</string>

    <string name="news_title_2">Характеристика: Диалог новостей</string>
    <string name="news_summary_2">Получайте уведомления о новых возможностях</string>

    <string name="news_title_3">Улучшение производительности</string>
    <string name="news_summary_3">Множество улучшений производительности для Photok</string>

    <string name="news_title_4">ПУСТОЙ</string>
    <string name="news_summary_4">ПУСТОЙ</string>
</resources>

---

*Translation made with [Stringlate](https://github.com/LonamiWebs/Stringlate).*

**Comment by leonlatsch** [comment]
Where?
