### ISSUE TITLE
[Feature] Photok Recovery Menu

### ISSUE THREAD

**Issue by leonlatsch** [leonlatsch/Photok#181]
**Feature Description**
Some users have problems with not being able to launch the hidden app from the phone dialer. Therefore I want to implement a recovery menu to open it again, since otherway the data is list.

The options for now should be:
- Open Photok
- Show app icon again
- Close

I want to show it in a specific way:
- Put the device in flight mode
- Open the fake phone dialer
- Open the fake phone dialer within 5 seconds again (also in flightmode)
- Redirect to Recovery Menu instead of Phone Dialer

**Comment by janez33** [comment]
Thanks god I'm so smart I came to Closed issues and thank you for this recovery feature 🕺
