### ISSUE TITLE
[Bug] Can't add pictures, videos or imports from backup

### ISSUE THREAD

**Issue by RequestPrivacy** [leonlatsch/Photok#192]
**To Reproduce**
1. Install Photok and set-up a PIN
2. In the newly created safe click on the + menu at the bottom right
3. Click on one of the 3 different options for importing
4. Nothing happens, except a small glitch where it seems as if the background of Photok seems to be focused again (i.e. the darkened background picture of the safe is white again).

**Expected behavior**
I had Photok installed on the same Pixel but on Android 12, where it worked properly (so adding e.g. personal pictures worked).

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: worked on CalyxOS with Android 12, now on GrapheneOS with Android 13 it isn't working for me anymore
 - Version 1.4.1

**Additional context**
[GrapheneOS](https://grapheneos.org/) is an hardened OS which implements multiple additional layers for protecting the device owners security and privacy. It may be that there is something which breaks Photoks ability to import data e.g. by disallowing the file chooser to open. Although this would be the first occurrence of such a thing (at least for me) and I gave my best to give Photok all permissions it needed I can't rule such a thing out.

Furthermore I tried an install from F-Droid and directly with the APK from the github releases section and also in the owner profile and a dedicated user profile. It never worked...

EDIT: 
I just installed Photok on another device (Android 11 Tablet) and the "Allow file access"  dialog which gets prompted indeed never appears on my Pixel.

**Comment by leonlatsch** [comment]
Hi,

I have already experienced this during development. 

Seems to be an issue with Android 13. I will try my best to fix this ASAP. 

Thank you for reporting :)

**Comment by canary5** [comment]
Can confirm on 6a pixel, stopped working after a13

**Comment by leonlatsch** [comment]
Fixed in #193 and will be released with 1.4.2 within the next days

**Comment by RequestPrivacy** [comment]
Thanks for the quick fix. Will try out on 1.4.2 once it's released
