### ISSUE TITLE
[Security] Meta.json inside backup file contains unencrypted plaintext file information accessible by 3rd parties

### ISSUE THREAD

**Issue by Mhowser** [leonlatsch/Photok#223]
**Describe the bug**
When a Photok backup file is created, the app generates a Compressed ZIP file containing the encrypted files and a file called `meta.json`. This JSON file contains all filename information and a partial password hash _in plaintext_.

**To Reproduce**
1. add files to Photok Vault
2. go to the settings section and select Backup
3. open the compressed backup file and open `meta.json` in your preferred text editor.
4. Profit?

**Expected behavior**
All contents of a Photok backup file should be encrypted, ZIP compression supports password-protection which should be utilized in this situation.

**Screenshots**
![meta json photok](https://github.com/leonlatsch/Photok/assets/24195572/9088750b-e427-465a-a758-41f63c150451)

**Smartphone (please complete the following information):**
 This applies to all devices running Photok 1.5.0 or less

**Additional context**
None

**Comment by leonlatsch** [comment]
Also using zip password protection would be a new feature request.

**Comment by leonlatsch** [comment]
I just don't have that much time anymore fore side projects. Since I created Photok, I moved out, started working full time (also Android Dev), etc.
I do my best to reply to issues and emails. I keep maintaining the app abut I simply don't have the time for feature development. But thats the nice thing about open source. Other people can implement those features. I will always look at those prs and create new releases :)

**Comment by Mhowser** [comment]
Thanks for clarifying your position, I always appreciate a different perspective on how different developers manage their projects. And thanks for making us a great app! I wish I had the experience to contribute more to this project. Maybe someday I'll get there too...

**Comment by leonlatsch** [comment]
This will not be worked on right now. 

If anyone would like to implement Zip Protection, go ahead. 

A workaround would be to password protect your backup yourself for now.
