### ISSUE TITLE
[Contribute question] Adding new localisation

### ISSUE THREAD

**Issue by f1refa11** [leonlatsch/Photok#229]
Hello, i would like to contribute to your project by adding a Russian localisation, but because I don't know Java, I don't understand how do I add a new localisation to my fork of this project.

Can you explain to me how to add a localisation to your project?

**Comment by leonlatsch** [comment]
You can look at prs from the past like #231 or #190 .

You just have to add a folder in app/res/ (app/res/values-ru for russian). Then you copy the strings.xml from app/res/values into your values-ru folder and change the values to your translation.

Like I said have a look at the links above for examples.

Please close if this answers your questions

**Comment by f1refa11** [comment]
Made a PR.
