### ISSUE TITLE
[Feature] Add option to delete files after export

### ISSUE THREAD

**Issue by wu4339** [leonlatsch/Photok#247]
Provide the option to delete files in the app when exporting

**Comment by BIBLETUM** [comment]
Can i do this issue? Is it about deleting all files after making a backup?

**Comment by leonlatsch** [comment]
Its the exact opposite of "delete imported files".

So a file in photok should be removed from photok once it was exported to the regular file system.

**Comment by leonlatsch** [comment]
Of course with a option in the settings. Same as delete imported images

**Comment by leonlatsch** [comment]
Implemented in #259
