### ISSUE TITLE
Find a privacy friendly analytics tool

### ISSUE THREAD

**Issue by leonlatsch** [leonlatsch/Photok#277]
In order to get some useful anonymous data about Photoks usage I want to use a privacy first anonymous analytics tool.

*Feel free to suggest some*

**Requirements:**
* Non proprietary / open source
* Compliant with F-Droid Guidelines
* Preferably available as container application for self hosting
* Preferably Java/Kotlin SDK

**Alternative**
Build a own, very simple service to count users

**Comment by leonlatsch** [comment]
Tool I found myself:
* https://countly.com/
* https://www.offen.dev/
* https://github.com/milesmcc/shynet
* https://ackee.electerious.com/

**Comment by yuno-tw** [comment]
Will this be opt-in, or will an opt-out be possible?

**Comment by leonlatsch** [comment]
I hope to find a tool that legaly doesn't require an opt it. Also I don't plan to collect any person related data.

But this is a very loose concept right now. The current motivation is: I want to know how many users I have overall. Currently I only know how many google play users I have

**Comment by leonlatsch** [comment]
Seems like countly.com is the best candidate for using a pre built tool. 

Or a custom open tool is required. 

For more ideas please see #289
