### ISSUE TITLE
[Feature] Optimize the display of open pictures

### ISSUE THREAD

**Issue by wu4339** [leonlatsch/Photok#282]
Now Click to open the picture will be black, and then pop up from the bottom，hope open picture display directly。

**Comment by leonlatsch** [comment]
Unfortunately this is limited by the device. The image is decrypted  in full size when you open it. Therefore it may take some more time. 

Hopefully this can be improved when the image viewer is rewritten in compose, which then will use coil for loading and not my custom implementation with glide. 

So I will close this one for now.
