### ISSUE TITLE
[Feature] Layout improvements for the new gallery

### ISSUE THREAD

**Issue by yuno-tw** [leonlatsch/Photok#283]
**Is your feature request related to a problem? Please describe.**
Since the new gallery is live I gave it a try, and while the bigger images look great, some design decision aren't optimal in my opinion. (Maybe some of it was present before but I just noticed it now :woman_shrugging:)

1. The lock button is missing and there is now no way to lock the gallery without closing the app.
2. The settings aren't used often enough to justify a bottom app bar, which takes away a lot of space.
3. The logo permanently hovering over the images is a bit distracting. I would expect, that the top bar can be scrolled out of view.
4. When selecting, the selected images get a dark overlay. This highlights the not selected images which is counterintuitive. 

**Describe the solution you'd like**
1. Bring back the button
2. Move the settings back to a button in the top bar. In the old gallery they were on the right side, but I'd suggest putting them on the left side. In case more  buttons are needed the button on the left side could be exchanged with an option to open a side bar, which contains them.
3. Use a solid top bar without transparency. When scrolling down the bar is scrolled out of view, when scrolling up it reappears (similar to how address bars on mobile browsers work). The reappearing part is only necessary when adding interactive elements like buttons to the top bar.
4. Either use the old approach of shrinking the selected images a bit down. Inverting the effect might also work (dark overlay for not selected images). Note that this point is very subjective, since e.g. Samsung Gallery also darkens selected images, but the effect in Photok is much stronger. Tweaking might be an option as well.

**Additional context**
Note that those are my personal opinions so feel free to disagree.

**Comment by leonlatsch** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Since the new gallery is live I gave it a try, and while the bigger images look great, some design decision aren't optimal in my opinion. (Maybe some of it was present before but I just noticed it now :woman_shrugging:)
> 
> 
> 
> 1. The lock button is missing and there is now no way to lock the gallery without closing the app.

This was intentionally removed, because the new gallery design didn't have a place for it.

> 
> 2. The settings aren't used often enough to justify a bottom app bar, which takes away a lot of space.

I agree. This is a little foreshadowing for the album's feature which will be added there aswell. It's not recommended to have less than 3 elements in a nav bar but that's how it is for now.

> 
> 3. The logo permanently hovering over the images is a bit distracting. I would expect, that the top bar can be scrolled out of view.

This is part of the new design. Might be replaces with something else in the future. Maybe to display the date. 

All in all I can say, that a solid top bar is just out of date and I won't return to this design. 

> 
> 4. When selecting, the selected images get a dark overlay. This highlights the not selected images which is counterintuitive. 

Actually, I have looked at many other gallery apps and just did the same.
