### ISSUE TITLE
[Feature] Multiple safes support

### ISSUE THREAD

**Issue by furu-ame** [leonlatsch/Photok#284]
**Is your feature request related to a problem? Please describe.**
When you want to import, let's say, a document in a safe full of photos, things quickly turn a bit messy. Not only the document you are looking for is buried amongst a pile of unrelated media, you also have to take your time to find it. It's incredibly annoying.

**Describe the solution you'd like**

1. When a safe is unlocked, make an option to create another safe in the settings tab.
2. Guide the user through the setup. 
3. When the safes are locked and the user is shown the password screen, the password entered will open the said safe. 

**_For example, if the user types the password for the document safe, the said safe opens. Same goes for any over safes created._**

Also, when a user tries to reset a safe, only the unlocked one will be deleted, but not all of the others.

**Describe alternatives you've considered**
Using the work profile feature is a pain to navigate and  to utilise, so that's a no-go.

**Additional context**
Letting the user choose what safe to unlock not only will require the naming of every safe, but it's name might hint a malicious actor of what's inside.

**Comment by leonlatsch** [comment]
This was already requested in #197

Feel free to add your thoughts there. I will close this as duplicate
