### ISSUE TITLE
App cannot be moved to SD card

### ISSUE THREAD

**Issue by jebbgrenham** [leonlatsch/Photok#294]
**Is your feature request related to a problem? Please describe.**
The app seems to have a flag set which disallows it from being moved to SD card. As the app doesn't have any option for storage location, this flag prevents it from storing the database anywhere other than the system storage. As it's a gallery app, the content can quickly become massive and really ought to be stored on external storage by default. 

**Describe the solution you'd like**
Presuming that the devs don't have time to add feature to store database on SD card, the quick fix would be removing whatever flag is set which prevents the app from being moved to SD card.

**Describe alternatives you've considered**
- Moving app to SD card. Not permitted.
- Searching photok settings for any way to move the database storage location to SD card. None found. 
- Finding an alternate open source app with similar features. Not found.

**Comment by leonlatsch** [comment]
Maybe its `android:allowBackup="false"`. This is for preserving the app from being backed up by google backup stuff (since this may destroy data integrety). But if anyone is curious, try it out

**Comment by jebbgrenham** [comment]
Where would this need to placed in source? I have written lots of js, python, php but never dabbled in android. Time to learn I guess!

**Comment by leonlatsch** [comment]
Such things are inside of AndroidManifest.xml

**Comment by jebbgrenham** [comment]
I think it might just need android.installLocation="auto"

**Comment by jebbgrenham** [comment]
I added the line, built the APK, tried to install on my device but just got "app not installed". I'm in over my head, and I might keep working on this but someone who's a bit more set up for deployment might have better luck.

**Comment by leonlatsch** [comment]
Maybe. But "app not installed" can have many sources. I suggest to try a clean install

**Comment by jebbgrenham** [comment]
I wanted to, I just was hoping to do it without having to rebuild my entire gallery after uninstalling my current installation. Hence my post in discussion about restoring from backup. Without that ability, I'll have to try find another device to test the build on. Still not sure why my install doesn't allow restoring from backup.

**Comment by jebbgrenham** [comment]
Unfortunately, this does not actually work. Meant to post earlier, just ran out of time. The app can be moved to the SD card but the database remains in internal memory.

**Comment by leonlatsch** [comment]
Do you mean only the database or also the files? The database itself is very small

**Comment by jebbgrenham** [comment]
The encrypted media (which I assumed was stored as/in database) does not follow the app onto the external SD. The media is really the only issue as it can be sizeable but my fix did not fix it as expected.

**Comment by leonlatsch** [comment]
@jebbgrenham  Okay. Yes its stored in internal app storage, but not in the SQLite database. They are in the "files" directory of the app and just stored as regular files. The database is just like an index.
