### ISSUE TITLE
Might you removing this permission? It is unnecessary

### ISSUE THREAD

**Issue by serrq** [leonlatsch/Photok#310]
![1000113463](https://github.com/leonlatsch/Photok/assets/113377431/8b35beec-7443-4ff4-902a-8598e13d25df)

**Comment by leonlatsch** [comment]
This is requested by a library not by the app itself.

**Comment by leonlatsch** [comment]
> > This is requested by a library not by the app itself.
> 
> Honestly, can you do something to solve this issue?
> 
> Changing the library, repairing the library, etc.

I have had a look what is requesting it. its [Exoplayer Core](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/AndroidManifest.xml).

Photok basically 100% relies on Exoplayer to play its videos.

So not really an option to replace it, BUT: According to [this issue](https://github.com/google/ExoPlayer/issues/6019) the devs made it possible to explicitly disable the permission. I will try that

**Comment by leonlatsch** [comment]
Seems like this is not released yet. I will create a PR and wait for the next stable release of exoplayer for a release
