### ISSUE TITLE
[Bug] Animated GIFs not working anymore

### ISSUE THREAD

**Issue by jfml** [leonlatsch/Photok#331]
**Describe the bug**
Hi, I noticed that animated .gifs are not working anymore (probably due to the gallery change?), can't really say since when but it was working in the past. 

**To Reproduce**
1. Open Photok
2. Either import a .gif or click on one you already have
3. Internal picture viewer/slide show opens and shows a still gif but animation is not playing anymore.

**Expected behavior**
I would hope that the viewer could viewer play animated .gifs. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Fairphone 5
 - OS: Stock Google Android 13
 - Browser: So many, I guess Default Webview?
 - Version: No idea + __ +

**Additional context**
I know .gifs aren't cool anymore but I like them since the can play animations in a loop (if gif animations are not possible maybe it would be an option to loop videos?).

Thanks for the amazing app and keep up the good work ^ __ ^

**Comment by leonlatsch** [comment]
Oh man. Thats my fault. 

I replaced the image library that was used for scaling images and forgot to implement this feature 🫠

**Comment by jfml** [comment]
Haha, no worries! I'm glad to hear that it seems to be possible to fix this so I'm all good ^ __ ^
