### ISSUE TITLE
Importing from Android sharing system.

### ISSUE THREAD

**Issue by VioletFalcon** [leonlatsch/Photok#35]
**Is your feature request related to a problem? Please describe.**
Additional steps are required if you want to import a photo from an encrypted base, such as an instant messaging app.

**Describe the solution you'd like**
Make it possible to import photos through the Android sharing system.

**Additional context**
If photos are stored in an encrypted database, you need to save them in the normal phone storage before importing in Photok, I'm not sure if sharing function is secure or if this is a legit request, I just want to give an idea. Thanks for reading, and thanks for the app I really wanted this!!

**Comment by leonlatsch** [comment]
This may be a good idea. I will have a look at it, once I get back home in the new year.

Thank you for the idea and for enjoying Photok :)

**Comment by leonlatsch** [comment]
This feature is now in development and will be released with the next version of Photok.

**Comment by leonlatsch** [comment]
Share to Photok was implemented and will be deployed with version 1.2.0.
