### ISSUE TITLE
[Feature] Support Android built-in backup mechanism (SeedVault)

### ISSUE THREAD

**Issue by jluttine** [leonlatsch/Photok#354]
**Is your feature request related to a problem? Please describe.**

It'd be nice to be able to automatically take backups (and then automatically sync those to a remote device). It's cumbersome to do the backups manually because one wouldn't remember/bother to do those frequently.

**Describe the solution you'd like**

At least recent LineageOS has built-in backup mechanism with SeedVault - I don't know about other Androids. Currently, Photok doesn't support it, but if it did, then Photok data could be backed up together with all other apps. The photos/videos being encrypted of course. This way, Photok wouldn't need to implement its own automatic backup/syncing solutions, but just support the existing SeedVault.

This could be opt-in because some people might not want this to happen by default.

**Describe alternatives you've considered**

Photok-specific implementation would be an alternative but I think it's better to just support the already feature-rich existing solutions like SeedVault.

**Additional context**

**Comment by leonlatsch** [comment]
Good idea 👍 

This might be one way to do it. Whats also planned for the future, are external vaults. So that they could be located on SD card or any cloud location. Will keep this issue for now, if anyone wants to implement this, but I'd prefer the external vault solution

**Comment by claymorwan** [comment]
> So that they could be located on SD card or any cloud location.

About say cloud sync, it would he nice to maybe use rclone, that way we could have cloud sync to a lot of different cloud service
