### ISSUE TITLE
[Feature] Importing Videos 

### ISSUE THREAD

**Issue by ebanDev** [leonlatsch/Photok#36]
**Is your feature request related to a problem? Please describe.**
I'd like to have an option to import videos as well 😁

**Comment by leonlatsch** [comment]
This is something I already had in mind. I will have to think about it, but it's on my list.

**Comment by fux0r2009** [comment]
> This is something I already had in mind. I will have to think about it, but it's on my list.

It would be fantastic to have videos as well !!

**Comment by leonlatsch** [comment]
Unless someone eles implements this, this feature is going to be implemented in a future release.
I don't want the new features in 1.2.0 to be held back "so long", because this may take kinda long to implement.

But I will do it eventually.

**Comment by fux0r2009** [comment]
> Unless someone eles implements this, this feature is going to be implemented in a future release.
> I don't want the new features in 1.2.0 to be held back "so long", because this may take kinda long to implement.
> 
> But I will do it eventually.

Yes as long as it will be implemented in the future it's not a problem, looking forward to 1.2.0 !!! Best regards :)

**Comment by ebanDev** [comment]
When do you approximately think the v2.0.0 will be released ?

**Comment by leonlatsch** [comment]
Since I am working on this alone in my free time, it really depends on how much time I have for it.

**Comment by ebanDev** [comment]
No problem, good luck with your exams 💪

**Comment by leonlatsch** [comment]
Thank you, alongside with collections, this is next on the list.
For more info about release roadmap see the [KanbanBoard](https://github.com/leonlatsch/Photok/projects/1)

**Comment by cm157** [comment]
Looking forward to this too

**Comment by leonlatsch** [comment]
@cm157  Working on it right now on twitch 😄 (https://twitch.tv/leonlatsch)

**Comment by herkyl** [comment]
@leonlatsch I see the video feature is a PR already, when do you think it will be released 😍 ?

**Comment by leonlatsch** [comment]
> @leonlatsch I see the video feature is a PR already, when do you think it will be released 😍 ?

This will take some time. Development is currently paused due to exams and so on.

I don't know when I will be able to continue development. Maybe something next month, maybe laternthis year. It will depent on how I can find time.

**Comment by herkyl** [comment]
@leonlatsch good luck with your exams!

**Comment by leonlatsch** [comment]
News!

The feature is now experimentally "working". Will now be tested by us.
