### ISSUE TITLE
[Help] cant access app from dialer

### ISSUE THREAD

**Issue by Dreadloaf** [leonlatsch/Photok#362]
I used the hide app feature to launch from dialer. I used the default code "*#*#1337*#*#". This doesnt work for me. It only gives me the invalid mmi code notif. Ive also tried many combinations of the hashes and asterisks and cant get it to work. I am using the hidden app and not the regular phone dialer. Sorry if this isnt the right way to ask for help, im new to github

**Comment by Dreadloaf** [comment]
I've also gotten it to work once by typing "*#1337*#" but it will not work again

**Comment by leonlatsch** [comment]
Hey,

You can see a FAQ about this topic here: https://github.com/leonlatsch/Photok/discussions/106

This helps resetting the hidden app
