### ISSUE TITLE
[Feature] Image organization solution

### ISSUE THREAD

**Issue by Tisckkytt** [leonlatsch/Photok#41]
**Is your feature request related to a problem? Please describe.**

When the vault becomes populated, it becomes hard to find desired pictures quicker.

**Describe the solution you'd like**

Any picture organization solution like Album, Folder or Tags will make it easier.

**Describe alternatives you've considered**

I think maybe a tagging solution will fit best with this app rather than having folders/albums. So if an option added to tag everything at the time of adding to the vault, then later a tag search solution will help sort them.

**Additional context**

There's an app called TagSpaces (FOSS), which let's tag files by renaming or by using a sidecar file. Maybe that's overkill for this app, just for reference.

**Comment by leonlatsch** [comment]
Thats a good Idea. #37 will implement a import overview dialog. Could use that for normal Input too and add tags there.

**Comment by fux0r2009** [comment]
Hello, first thanks for the wonderful software very much needed, I would like to add that tags are good but for a lot of people (me included) folders/albums are far more important and useful than tags so it would be really wonderful if you could implement a folder feature in a future release. again thanks for the great work :)

**Comment by leonlatsch** [comment]
Tags are much easier to implement, but I think most of the users are used to albums rather than tags. (Me included).

So the feature would look like this:

You can import photos as usual. Once you create an album, the gallery won't show all photos. It will show the created album and a "All Photos" album. I don't know if its going to take place in the current release (1.2.0).

**Comment by fux0r2009** [comment]
amazing yes that would be very good! again thank you very much for this wonderful work 💯

**Comment by Tisckkytt** [comment]
The reason I suggested tag is that, tags could act as albums but at the same time when assigned multiple tags to a single photo it could be a powerful sorting method.

The idea is - Once we've assigned some tags to a picture, the tagnames will appear as a chip

**Comment by Tisckkytt** [comment]
Sorry, github very conveniently placed the 'Close with comment' button under the text field.

**Comment by leonlatsch** [comment]
I'd say albums and tags are not excluding each other.
Maybe do an an album feature first and if its not enough, we can do a tag feature.

I think, I will start asking more people about their opinion.

**Comment by fux0r2009** [comment]
Yes tags are good to have but most people don't bother with writing tags  (me included I can confirm that none of my friends or colleagues use them either just as an example) but albums on the other hand are a must but having both would definitely be awesome :) but as  @leonlatsch said the priority should be toward what most people use!  
And "I will start asking more people about their opinion." is always a good move but I am confident my earlier statement will be confirmed hhh. 

Anyway @leonlatsch  is our open source hero 👍 👍 👍

**Comment by leonlatsch** [comment]
So I have decided to implement albums in this release and maybe add tags in the future.
Albums are just much more accessable.

**Comment by leonlatsch** [comment]
I did some concepting for the UI and came up with this:

- I think a tab layout will fot best.
- Also, a favorite tab would fit very nice.
- I might try to also implement it
- If it gets too big, it will be a seperate issue

![image](https://user-images.githubusercontent.com/50983026/105683186-a5ffca00-5ef3-11eb-837a-9737d169c91d.png)

**Comment by Tisckkytt** [comment]
I'm very fond of the layout of Google's Gallery Go. I'd request you to have a look on that.
Tabs at the bottom & albums at the top & all pictures in between, it's very simple yet functional UI design.

**Comment by leonlatsch** [comment]
Sooooooo, after planning this out, I came to this conclusion:

- I will implement Collections
- They will work like tags but look like albums.
- You can add as photos to as many collections as you want
- The UI design will be as shown above

## **BUT**

This is a very big feature. It requires database migrations, chaning backup, and so on.
So this will be implemented in a new major version `2.0.0`. So it wont be in the next release.
Also I dont want to hold the new feature back till this is ready.

I will now clean up version `1.2.0` and release it for good with the new features.
If any of you are curious, on the new release plan, just look at the KanbanBoard.

**Comment by leonlatsch** [comment]
## Update
An update to Room 2.4.0 should happen before this gets worked on. Version 2.4.0 automates database migrations :)
2.4.0 is currently in alpha04

**Comment by GovindasOM** [comment]
I'm really excited for this feature, can't wait to move my entire gallery to Photok once this gets made

**Comment by BlastboomStrice** [comment]
Idea here: what about when you are moving an image to a collection, it gets moved to a different subfolder inside the main folder? One can have thousands pictures and tens (or hundreds of folders), so I think it'd be easier to keep it organised if there are folders for each collection. Also it may speed up loading times.

An issue this may have is that paths may become too long (as with lockmypix), causing issues with file transfering. (But then again, I can find workarounds to transfer the files from the lockmypix gallery).

A possible solution would be to create single level folders (to restrict creating a subfolder inside a subfolder) and maybe link "sub-collections" to a bigger one without putting them in the same folder.

Example:
I have 2 collections (A and B) with their seperate sub-folders (A and B) inside the main photok folder. I want them to be under the collection C. I create a collection C with its own subfolder. I get to A collection and press link and select C. That way, a shortcut is created inside subfolder C leading to A.

PS. Collections should be able to contain both images and videos in the same subfolder. Maybe the could be contained in different folders inside the subfolder, but not appear as a different collection.

I've also noticed that currently the imported items are placed inside the app data. Lockmypix has them stored externally with encrypted file names. I think having them externally makes it easier to backup things (like, just copy paste from phone to pc) which can be very useful when you don't have enought space on your phone to create a backupand move it to an external device.

So what I purpose is:

Store files externally and have them like the diagram in the pic below:
![Photok](https://user-images.githubusercontent.com/65232133/130213314-099c0eb3-53b3-4170-945a-5cd106657a40.png)

**Comment by leonlatsch** [comment]
> Idea here: what about when you are moving an image to a collection, it gets moved to a different subfolder inside the main folder? One can have thousands pictures and tens (or hundreds of folders), so I think it'd be easier to keep it organised if there are folders for each collection. Also it may speed up loading times.
> 
> An issue this may have is that paths may become too long (as with lockmypix), causing issues with file transfering. (But then again, I can find workarounds to transfer the files from the lockmypix gallery).
> 
> A possible solution would be to create single level folders (to restrict creating a subfolder inside a subfolder) and maybe link "sub-collections" to a bigger one without putting them in the same folder.
> 
> Example:
> I have 2 collections (A and B) with their seperate sub-folders (A and B) inside the main photok folder. I want them to be under the collection C. I create a collection C with its own subfolder. I get to A collection and press link and select C. That way, a shortcut is created inside subfolder C leading to A.
> 
> PS. Collections should be able to contain both images and videos in the same subfolder. Maybe the could be contained in different folders inside the subfolder, but not appear as a different collection.
> 
> I've also noticed that currently the imported items are placed inside the app data. Lockmypix has them stored externally with encrypted file names. I think having them externally makes it easier to backup things (like, just copy paste from phone to pc) which can be very useful when you don't have enought space on your phone to create a backup and move it to an external device.
> 
> So what I purpose is:
> 
> Store files externally and have them like the diagram in the pic below:
> ![Photok](https://user-images.githubusercontent.com/65232133/130213314-099c0eb3-53b3-4170-945a-5cd106657a40.png)
> 

I will look into that later today, but let me say if me change this THIS much its defenetly not happening with this issue.

**Comment by yephny** [comment]
Are you still considering to implement the features you mentioned in this issue?

**Comment by leonlatsch** [comment]
> Are you still considering to implement the features you mentioned in this issue?

Yes. This feature is the most requested one for Photok. There is just no active development for the app right now.

**Comment by igarca** [comment]
Hey! I just wanted to thank you for the work, Photok is great! I encourage you to continue working on it:-)))

**Comment by leonlatsch** [comment]
> Hey! I just wanted to thank you for the work, Photok is great! I encourage you to continue working on it:-)))

Thank you, I am doing my best to keep Photok at least up to date, with libraries and Android versions. Maybe I can find some time implementing this some time.

But keep in mind: Photok is open source, anyone could implement this :)

PS: I am currently re-implementing the gallery as a base for this, since much has changed in Android since I created it.

**Comment by plutonium-239** [comment]
Hi
I would love to contribute, and I'm just trying to understand the code structure. (Kotlin is not my first lang, but I'll still try)
However, it looks like you've been making a lot of other changes as well, like the UI navigation bar, the "Single Live Event", etc. and it's all a bit overwhelming to keep track of 😅 (especially gradle refusing to build/start itself/whatever, even though I've used the same files as in #135 ) so no promises from me!
I hope you get to a releasable point soon! (are there any estimates?)
Thanks!

**Comment by plutonium-239** [comment]
Hey @leonlatsch, I tried to get it to build but this error stumps me: 
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.util.ResourceBundle.setParent(java.util.ResourceBundle) accessible: module java.base does not "opens java.util" to unnamed module @79e2c065
```
I have freshly cloned the repo and fetched the pull request #135.

**Comment by leonlatsch** [comment]
There is a branch I think with the new gallery https://github.com/leonlatsch/Photok/tree/gallery_rewrite

But its not much in there yet. (Haven't been able to do much for Photok in the meantime).
The big problem is, that Android changes so fast and I cannot keep up at a rate I would like to. So yeah, rewriting the gallery first in a clean way is I think a base for this to be implemented in a good way.

**Comment by yuno-tw** [comment]
> But keep in mind: Photok is open source, anyone could implement this :)

I was thinking about implementing this. But seeing how some development happened recently, I figured I'd ask whether you plan to do this yourself in the near future @leonlatsch, before I spend the time to get up and running.

**Comment by leonlatsch** [comment]
> > But keep in mind: Photok is open source, anyone could implement this :)
> 
> 
> 
> I was thinking about implementing this. But seeing how some development happened recently, I figured I'd ask whether you plan to do this yourself in the near future @leonlatsch, before I spend the time to get up and running.

Yes, I started working on Photok a bit recently. The new gallery is a  base for this feature, so I might start in the near future.

**Comment by leonlatsch** [comment]
Good news. The new gallery is finished and I started working on this.

**Comment by yephny** [comment]
Great news! Do you plan on rolling out the new gallery before implementing this? I'd love to test the new gallery out.

**Comment by leonlatsch** [comment]
New Gallery is live on all stores with version 1.6.0

**Comment by leonlatsch** [comment]
The albums feature is finished. Feel free to test on develop. 1 thing is missing. For a release the milestone has to be done.
