### ISSUE TITLE
[Feature] Hide Photok Icon and Open the Photok by phone Dialer

### ISSUE THREAD

**Issue by fux0r2009** [leonlatsch/Photok#44]
**Is your feature request related to a problem? Please describe.**
Not really a problem but just for more stealth and privacy.

**Describe the solution you'd like**
For even more Stealth some apps give the option to hide the Icon of the app as if it is not installed and it can be opened by dialing a code on the phone dialer app which then brings the vault app and ask for password like normal. So if a phone is shared the other user won't even know that there is a Photok Installed unless he make a deep inspection :)

**Additional context**
I am aware that this not really something to prioritize but in the future it would be nice addition to Photok

**Comment by leonlatsch** [comment]
This should't be too hard to implement. I'll do some research tomorrow.
Cloud even fit in this release.

**Comment by leonlatsch** [comment]
Did some research, should be able to add the feature in 1.2.0

**Comment by fux0r2009** [comment]
Wow Didn't expect this so fast your are the Best 👍 👍 👍

**Comment by leonlatsch** [comment]
### Refarences for implementation:

- https://stackoverflow.com/questions/8398514/hide-application-icon
- https://stackoverflow.com/questions/56900946/how-to-detect-outgoing-call-number-in-android-q

**Comment by leonlatsch** [comment]
So I was implementing the feature when I found out [that google is really strict about call permissions. ](https://support.google.com/googleplay/android-developer/answer/10208820?visit_id=637463534264585660-3751760359&rd=1#zippy=%2Calternatives-to-common-uses%2Cpermitted-uses-of-the-sms-call-log-permissions%2Cexceptions%2Cinvalid-uses)

I don't know if we can really do this feature. Need to do some more research.

**Comment by leonlatsch** [comment]
@fux0r2009 do you have any other idea on how to open the app, when the icon is hidden?

**Comment by leonlatsch** [comment]
> So I was implementing the feature when I found out [that google is really strict about call permissions. ](https://support.google.com/googleplay/android-developer/answer/10208820?visit_id=637463534264585660-3751760359&rd=1#zippy=%2Calternatives-to-common-uses%2Cpermitted-uses-of-the-sms-call-log-permissions%2Cexceptions%2Cinvalid-uses)
> 
> I don't know if we can really do this feature. Need to do some more research.

Turns out there is a way with a static secrect code like *#*#123#*#* without any permission.

**Comment by fux0r2009** [comment]
> > So I was implementing the feature when I found out [that google is really strict about call permissions. ](https://support.google.com/googleplay/android-developer/answer/10208820?visit_id=637463534264585660-3751760359&rd=1#zippy=%2Calternatives-to-common-uses%2Cpermitted-uses-of-the-sms-call-log-permissions%2Cexceptions%2Cinvalid-uses)
> > I don't know if we can really do this feature. Need to do some more research.
> 
> Turns out there is a way with a static secrect code like '_#_#123#_#_' without any permission.

Yes that's what I had in mind and it's also what is used in other apps with the same feature! looking forward to the next release :)

**Comment by fux0r2009** [comment]
> @fux0r2009 do you have any other idea on how to open the app, when the icon is hidden?

You could also make a feature to disguise app icon with a different generic app name like File Explorer or QR code Scanner... etc for those who don't want to hide the app but just make it less obvious. just a proposition as I personally still prefer to completely hide the app but some people like the other way of disguising the icon too.  anyway It not as important as hiding so up to you @leonlatsch

**Comment by leonlatsch** [comment]
> > @fux0r2009 do you have any other idea on how to open the app, when the icon is hidden?
> 
> You could also make a feature to disguise app icon with a different generic app name like File Explorer or QR code Scanner... etc for those who don't want to hide the app but just make it less obvious. just a proposition as I personally still prefer to completely hide the app but some people like the other way of disguising the icon too. anyway It not as important as hiding so up to you @leonlatsch

This might be the way to go. As of Android 9, the app icon will always be shown, unless its a system app. [Source](https://stackoverflow.com/a/22754642/12025158)

**Comment by fux0r2009** [comment]
> > > @fux0r2009 do you have any other idea on how to open the app, when the icon is hidden?
> > 
> > 
> > You could also make a feature to disguise app icon with a different generic app name like File Explorer or QR code Scanner... etc for those who don't want to hide the app but just make it less obvious. just a proposition as I personally still prefer to completely hide the app but some people like the other way of disguising the icon too. anyway It not as important as hiding so up to you @leonlatsch
> 
> This might be the way to go. As of Android 9, the app icon will always be shown, unless its a system app. [Source](https://stackoverflow.com/a/22754642/12025158)

I see well disguising the app is better than nothing :)
