### ISSUE TITLE
[Features] List of some propositions :  Support Password Attempts / Shake your phone to close / Support Fake Passcode

### ISSUE THREAD

**Issue by fux0r2009** [leonlatsch/Photok#53]
I have some features you could find intersting and they would enhence Photok a lot : 

**- Shake your phone to close Photok in a hurry** : This would come handy if you want to quickly close the app 

**- Support Password attempts and option to delete the encrypted database if n attempts are reached** 

**- Support Fake Passcode and show fake content when you input fake passcode** : just if forced to show the content hhh

Hope you find some of this propositions interesting... anyway thanks for giving us Photok the much needed open source vault :)

**Comment by leonlatsch** [comment]
I have created seperate issues for the suggestions I thought are good, so I will close this one.

Thank you for all of your contributions and your big interest in Photok. If you want, you can sumbit a pr and add yourself to contibutors,json. (Even if you didn't contribute code)
This way to will be shown in the app as a contributor.

**Comment by leonlatsch** [comment]
@fux0r2009 Have you red my comment? I can also add your entry for you.

**Comment by fux0r2009** [comment]
> @fux0r2009 Have you red my comment? I can also add your entry for you.

Yes sure that would be a honor hhh thanks 👍

**Comment by leonlatsch** [comment]
@fux0r2009 NIce.
You can sumbit it yourself or give me the needed information here.

I need: A display name, a short sentence about what you did, some way of contact (email or github name), and (if you have one), a website.

**Comment by leonlatsch** [comment]
Just look at [this](https://github.com/leonlatsch/Photok/blob/develop/app/src/main/assets/contributors.json) file, if you need context.

**Comment by fux0r2009** [comment]
Sure here hope it :    

  "contribution": "Proposing ideas and reporting bugs",
    "name": "Robert",
    "contact": "Robert2077@protonmail.com",
    "website": "https://github.com/fux0r2009"

**Comment by leonlatsch** [comment]
Thank you, i will add this tomorrow. It will be in 1.2.0 :)

**Comment by fux0r2009** [comment]
> Thank you, i will add this tomorrow. It will be in 1.2.0 :)

Thank you very much
