### ISSUE TITLE
[Feature] Give the option to delete the imported images from the file system 

### ISSUE THREAD

**Issue by fux0r2009** [leonlatsch/Photok#55]
It would be cool if we could while importing images to photok get those some images automatically deleted from the (visible file system) after their are imported without having to worry about going through all originally imported files and deleting them manually after.

**Comment by leonlatsch** [comment]
This is also one of the things that were "planned in my head" :)
Thank you.

**Comment by fux0r2009** [comment]
> This is also one of the things that were "planned in my head" :)
> Thank you.

Happy to hear it, good job 👍
