### ISSUE TITLE
[Feature] Please consider using SHA3-512 instead of SHA-256 for much improved security

### ISSUE THREAD

**Issue by fux0r2009** [leonlatsch/Photok#56]
SHA-512 is more secure than SHA-256 so it would be best if you could implement this security upgrade to the password hashing function.

Also if SHA3-512 (3 generation of SHA) is available for android it would be highly recommended.

Best Regards 👍

**Comment by leonlatsch** [comment]
I am using SHA 256 on purpose. The files are encrypted with AES-256 so the key must uave 256 bits length.

**Comment by fux0r2009** [comment]
> I am using SHA 256 on purpose. The files are encrypted with AES-256 so the key must uave 256 bits length.

I see, I asked you because I read on cryptography forums that on 64bit processors it's always better to use SHA512 with AES 256 as it is more secure and faster (256 in AES is block size but SHA is used to derive the key so it don't have to be 256 bit) 

source : https://crypto.stackexchange.com/questions/41476/is-there-any-benefit-from-using-sha-512-over-sha-256-when-aes-just-truncates-it

anyway I am not arguing... You are the dev so you must know what your doing :) I was just thinking that maybe this suggestion could help but if not please feel free to close this suggestion 👍

**Comment by leonlatsch** [comment]
I would consider changing to SHA-512 if it app wasn't released already.
All the keys are SHA-526 and would be invalid.
Also all backups were invalid.

**IF** we do this at some point, we would need to somehow announce this and provice a way to "convert" old backups and safes.

I will keep this in mind but close the issue for now.

Thank you!
