### ISSUE TITLE
[Bug] Some photos have wrong orientation.

### ISSUE THREAD

**Issue by leonlatsch** [leonlatsch/Photok#57]
**Describe the bug**
Some photos have the wrong orientation when imported.

**To Reproduce**
This only happens on a few phones.

In my cases, it only happens with photos taken with the camera.
Also, I could only reproduce it on this devices:

- OnePlus 7 Pro
- Xiaomi Mi 9t Pro
- Xiaomi Note 7 with photos taken by google camera

**Technial Details**
I have no idea why this happens, but it has to do with the binary header added by the camera, I think.

**Comment by leonlatsch** [comment]
@fux0r2009 on which phone did you experience this?

**Comment by fux0r2009** [comment]
> @fux0r2009 on which phone did you experience this?

Xiaomi Note 7 with photos taken by google camera

**Comment by comparesheriff** [comment]
I added 4 Photos for testing with different orientation of the camera while taking the photos. The "normal" orientation is horizontal with the camera on the left side for me. I don't know whether it is different for other vendors. Photos taken with Xiaomi integrated camera

The only thing different between the four pictures is the EXIF-Tag "orientation", which is one of the following:
* "Horizontal (normal)"
* "Rotate 180"
* "Rotate 90 CW"
* "Rotate 270 CW"
 I have also seen EXIF-Tag "Unknown (0)" which didn't seem to have an influence.

### Normal
![Orientation_Normal](https://user-images.githubusercontent.com/73910438/105995931-f1f46f80-60a9-11eb-9c5b-1a5000851525.png)

### Rotate 90 CW
![Orientation_90](https://user-images.githubusercontent.com/73910438/105995921-eef97f00-60a9-11eb-9b5d-51551960f539.png)

### Rotate 180
![Orientation_180](https://user-images.githubusercontent.com/73910438/105995927-f02aac00-60a9-11eb-9c2c-8b23726ebbc6.png)

### Rotate 270 CW
![Orientation_270](https://user-images.githubusercontent.com/73910438/105995930-f15bd900-60a9-11eb-8f9b-57a4e577af17.png)

**Comment by leonlatsch** [comment]
So this was one hell of a headache.
Apperantly Bitmap ready orientation exif data and rotates itself, when displayed.
Together with @comparesheriff we have now created a method to normalize the bitmap after that.

This way everything is dispalyed correctly and keep the exif orientation data in the file.
