### ISSUE TITLE
[Bug] "There are no photos in your safe" even though there is still one image in the app.

### ISSUE THREAD

**Issue by fux0r2009** [leonlatsch/Photok#60]
**Describe the bug**
I noticed that when I add a photo than a second one and then delete one of them, a message in the background shows : "There are no photos in your safe" even though there is still one image in the app.

**I noticed that it happened when there is only one image left in the app.**

**To Reproduce**
**1. Add multiple photos 2 or more
2. delete all but one of them (leave one in the app)
3. See error: the message will show while there is still an image in the app**

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 7
 - OS: Android 10
 - Browser: Privacy Browser
 - Version 3.6.1

**Comment by leonlatsch** [comment]
I will look at this tomorrow.

**Comment by leonlatsch** [comment]
Reproduced on Stock Android 11.
Planned fix for 1.2.0.

**Comment by leonlatsch** [comment]
Fixed in 1.2.0 ✅
