### ISSUE TITLE
[Feature] Make the app auto lock after it was reduced (Home navigation button is used)

### ISSUE THREAD

**Issue by fux0r2009** [leonlatsch/Photok#61]
**Is your feature request related to a problem? Please describe.**
When the we exit the app by using the back navigation button the app locks automatically but when it is reduced using the home navigation button it doesn't lock automatically and stays open and can readily be accessed when using switch navigation button.

**Describe the solution you'd like**
Making the app lock automatically if if is reduced too, using the switch navigation button.

**Comment by leonlatsch** [comment]
This is already implemented (kind of).
The lock timeout acts in the background. If you set it to "immediately" it will lock, once you navigate from it.

**Comment by leonlatsch** [comment]
So basically, if its set so 3 Minutes, it will be locked if the app is in background for 3 Minutes.

**Comment by fux0r2009** [comment]
> This is already implemented (kind of).
> The lock timeout acts in the background. If you set it to "immediately" it will lock, once you navigate from it.

Yes you are right, sorry my bad, I didn't notice the lockout timer in settings.
