### ISSUE TITLE
Update adds proprietary dependency, breaking F-Droid support

### ISSUE THREAD

**Issue by IzzySoft** [leonlatsch/Photok#72]
With your last release, you decided to add a license dialog. Unfortunately, you chose [play-services-oss-licenses](https://developers.google.com/android/guides/opensource) – which drags in proprietary libraries: GMS. That will make it impossible for F-Droid to update to this version, as it violates the inclusion policy.

Luckily, there are [some alternatives available](https://gitlab.com/snippets/1896503#license-dialogs) (if you know more, suggestions are welcome). Matching the license of your app (Apache 2.0), [LicensesDialog](https://github.com/PSDev/LicensesDialog) may be a good choice. So may I suggest switching to that?

**Comment by leonlatsch** [comment]
Hmm, thats weird.
@DRSchlaubi implemented this and the [github](https://github.com/google/play-services-plugins) says its Apache 2.0.

IF this breaks the fdroid support, I will of cource replace it.

**Comment by leonlatsch** [comment]
I have red the snippet now. I will replace this with [SimpleLicenseDisplay](https://github.com/MarcDonald/SimpleLicenseDisplay) for version `1.2.1`

**Comment by IzzySoft** [comment]
The library itself is indeed Apache-2.0 – which is why it's so easy to fall into that trap. Personally, I already get suspicious if a packageName starts with `com.google.android.` It's not the first time Google lures people in with FOSS and, if enough are locked-in, replaces free stuff with things from its "walled garden". Look where Android went, what happened to many AOSP apps…

But no need for rants :wink: Thanks for reacting that fast! Please ping me when `1.2.1` has been tagged. My updater will then pull it to my repo for a pre-check – and if my library scanner confirms (as I expect it to) GMS to be gone, I'll immediately re-enable updates at F-Droid (and remove the AntiFeature from mine).

**Comment by leonlatsch** [comment]
After looking around at some alternatives, I used the old report tool again and implemented a layout myself, based on a json report.

I may extract this as a library later on for others to use.
It looks like this:

![image](https://user-images.githubusercontent.com/50983026/105978260-a2567980-6092-11eb-8496-c57447ea2f81.png)

**Comment by leonlatsch** [comment]
@IzzySoft `1.2.1` is now tagged.

**Comment by IzzySoft** [comment]
Looks like 1.2.2 is out and has the issue fixed. Will re-enable auto-updates on F-Droid then – thanks for fixing it that fast!

@leonlatsch should you make that a library and have it available in a repo, please give me a ping so I can add it to my list of recommended alternatives.

**Comment by fux0r2009** [comment]
Hi @leonlatsch still no FDroid update ? still on 1.1.3

**Comment by leonlatsch** [comment]
@fux0r2009 as you see @IzzySoft just turned updates back on 1 hour ago.
Version 1.2.2 will now be transfered to f-droid.

**Comment by fux0r2009** [comment]
> @fux0r2009 as you see @IzzySoft just turned updates back on 1 hour ago.
> Version 1.2.2 will now be transfered to f-droid.

Ok looking forward to it thanks :)

**Comment by IzzySoft** [comment]
@fux0r2009 it will still take some days to arrive. I fear we've clogged our signer with the load of new releases and updates produced in the past weeks (I spent multiple weeks full-time on that, and trained some new contributors who also started hammering away at the huge backlog we had). There must still be more than hundred APKs in the signing queue alone currently (I'm e.g. eagerly waiting for a specific one that got merged about a week ago). And signing is, for security reasons, still a manual process on an air-gapped machine…

**Comment by leonlatsch** [comment]
@IzzySoft I have moved the code to a library.

[GitHub](https://github.com/leonlatsch/OssLicenseView)
Its available on Jitpack.io

**Comment by fux0r2009** [comment]
@IzzySoft I see thank you for the clarifications and also thank you very much for all your hard work and I hope that in the future this process could still be automated while maintaining the same level of security 👍 

Best regards

**Comment by IzzySoft** [comment]
> I have moved the code to a library.

Thanks! Added it to my recommendation list :smiley:

> I hope that in the future this process could still be automated while maintaining the same level of security

We're on it. Sylvia is just taking the code of my library scanner (written in PHP) and adapts it for use with fdroidscanner (written in Python). So in the hopefully near future, such cases would be caught right at the start of a build automatically.

Oh, btw, if you're interested: My scanner is openly available. I finally managed to write a little guide, including some background. German version went live 8min ago: [Module in Apps identifizieren](https://android.izzysoft.de/articles/named/app-modules-2) – English one ("Identify modules in apps") will follow soon™ at the same URL.

**Comment by fux0r2009** [comment]
> > I have moved the code to a library.
> 
> Thanks! Added it to my recommendation list 😃
> 
> > I hope that in the future this process could still be automated while maintaining the same level of security
> 
> We're on it. Sylvia is just taking the code of my library scanner (written in PHP) and adapts it for use with fdroidscanner (written in Python). So in the hopefully near future, such cases would be caught right at the start of a build automatically.
> 
> Oh, btw, if you're interested: My scanner is openly available. I finally managed to write a little guide, including some background. German version went live 8min ago: [Module in Apps identifizieren](https://android.izzysoft.de/articles/named/app-modules-2) – English one ("Identify modules in apps") will follow soon™ at the same URL.

Wonderful News! I will wait for the English version to look at it since I only know "Danke" In German hhh

**Comment by IzzySoft** [comment]
OK, go for it then – I've just put it online a minute ago. Same URL (chooses the language depending on your browser settings – but has a "flag" in the upper-right corner if you don't like the choice :wink:)

**Comment by fux0r2009** [comment]
@IzzySoft Thanks!

By the way just wanna ask you if the following statement is true about Fdroid? : 

_**"The bulk of applications distributed through fdroid are signed by keys that belong to the fdroid maintainers, and which are kept online. This means that the fdroid maintainers themselves, or any attackers who compromise fdroid, are capable of pushing malware to your device."**_

And is so how vulnerable is Fdroid? Thanks

**Comment by IzzySoft** [comment]
Source? To my knowledge, that's incorrect:

* "keys that belong to the fdroid maintainers": wrong
* "and which are kept online": totally wrong. Signing happens on an air-gapped machine. The private keys are at no time exposed.

Evaluate the remaining parts yourself.

So again: source of that misinformation?

**Comment by fux0r2009** [comment]
@IzzySoft Thank you for your response and yes you are correct I was looking up same privacy focused messaging apps and I saw signal post on reddit as to why they don't want to make signal available on F-droid so I was wondering... But know you are clarifying things thanks!

**Comment by IzzySoft** [comment]
Are you saying that misinformation (posted at Github in 2013) was repeated on Reddit more recently – despite better knowledge, as mvdan clarified it back then? Because that then would mean intentional malign behavior and defamation. I'd never expected that deep a fall. If so, can you please give a link to that Reddit post?

**Comment by fux0r2009** [comment]
There was other reddit posts but they were referencing the same other post so I think its mostly just explanations as to why signal dev was against Fdroid publishing.

**Comment by IzzySoft** [comment]
Ah, OK. I knew Moxie is a bit strange, but that would have surprised me even more. Enough as it is. Thanks!
