### ISSUE TITLE
[Feature] add biometric auth and import any type of file support like zip apk etc

### ISSUE THREAD

**Issue by User1l0** [leonlatsch/Photok#77]

**Comment by leonlatsch** [comment]
- Biometic auth is already planned (#45)
- Videos are planned for the future (#36). Other file types may follow, but the main focus will be media files. Photok is not a encrypted file manager.

Thank you for your contribution, I will close this. Please look at the referenced issues.

**Comment by User1l0** [comment]
>Photok is not a encrypted file manager.
But it could be, photoc literally stores picture files in zip like archive container, it's not probem to add file support, if the tumbnail is the problem for the other files types, it can be default file icon thumb, its very useful feature, there's no other like app in f droid to support this simple encrypted archive container feature, so you can add and make easier for users to use less apps, and make devs to not make thousands of forks, also it would be nice if you add folder support to organise your encrypted files, please don't ignore this.

**Comment by leonlatsch** [comment]
So.

Photok is designed and made to be a gallery, and I will keep it like that.

But, I could imagine to support the type "file" in the future. If so, it won't become the main focus of this project.

**Comment by ralaud** [comment]
> there's no other like app in f droid to support this simple encrypted archive container feature

You could use Cryptomator (paid app, it is in IzzyOnDroid F-droid repo) for files. Or just create a veracrypt container and open it with EDS Lite.

In my opinion, there should not be files in Photok.

**Comment by fux0r2009** [comment]
> > there's no other like app in f droid to support this simple encrypted archive container feature
> 
> You could use Cryptomator (paid app, it is in IzzyOnDroid F-droid repo) for files. Or just create a veracrypt container and open it with EDS Lite.
> 
> In my opinion, there should not be files in Photok.

I second that I think photok should only support Photos, Videos and Audio files nothing more (Multimedia files) but it's true that we need a veracrypt like app for fdroid like EDS Lite but with the premium feautures!

**Comment by User1l0** [comment]
> > there's no other like app in f droid to support this simple encrypted archive container feature
> 
> You could use Cryptomator (paid app, it is in IzzyOnDroid F-droid repo) for files. Or just create a veracrypt container and open it with EDS Lite.
> 
> In my opinion, there should not be files in Photok.

Eds lite is bad and useless app compared  to photok,
The reason i prefer photok over eds is for very nice simplicity

**Comment by ralaud** [comment]
> I second that I think photok should only support Photos, Videos and Audio files nothing more (Multimedia files) but it's true that we need a veracrypt like app for fdroid like EDS Lite but with the premium feautures!

Yea sadly thats true.. EDS even the premium version has to many bugs and Cryptomator is expensive. 

We just need another app which can mount gocryptfs, for this, a filemanager would be necessary due to this necessarity files would not fit into Photok in my opinion.

To combine the structure of a filemanager and a simple gallery would not be easy I think. Try to search and open photos in a filemanager, thats not comfortable. The other way round you would need to hassle with files in a gallery, thats not comfortable either.

Due to this, I do not use EDS Lite (which is comparable with a filemanager) anymore. It was not comfortable for photos.
