### ISSUE TITLE
Support animated Gifs

### ISSUE THREAD

**Issue by thomasfrobieter** [leonlatsch/Photok#82]
I'd like to play animated gifs, they're currently stuck on the first frame.

**Comment by leonlatsch** [comment]
Since #36 will add importing videos, I will fix this simultaneously.

**Comment by leonlatsch** [comment]
This works fine:

```kotlin
Glide.with(context).asGif().load(data).into(imageView)
```

**Comment by leonlatsch** [comment]
Fixed in commit 26cc48a.
