### ISSUE TITLE
[Feature] Adding support for a second (or multiple) databases by password

### ISSUE THREAD

**Issue by fux0r2009** [leonlatsch/Photok#83]
**Is your feature request related to a problem? Please describe.**
Photok only support one encrypted database but sometimes users would like to have and option to present a fake database or a legitimate second database that can be accessed by typing it's corresponding password 

**Describe the solution you'd like**
The possibility to create a new database and accessing it by directly taping it's corresponding password ! 

**Additional context**
It would also be very convenient and useful if the databases could be managed (Added or deleted) by a button on the first screen of the app as for now the only way to delete the database is to clear the app data)

**Comment by leonlatsch** [comment]
Interesting idea, will add this to the backlog for now.

Btw: You can reset the app in the settings under "Advanced".

**Comment by fux0r2009** [comment]
@leonlatsch  thank you, Yes I know you have a lot of requests and you are already doing a fantastic job and the more features you add the better but of course it's going to be on your own pace and when ever you can and want so no worries my friend 🥇
