### ISSUE TITLE
[Feature] Import whole (+nested) folders.

### ISSUE THREAD

**Issue by fourteen-1** [leonlatsch/Photok#97]
**Is your feature request related to a problem? Please describe.**
Problem is that i can't have folders in-app to categorize my photos as they currently are. i dont want all my photos randomly in one place. Also not being able to import whole folders into Photok is a huge problem.

**Describe the solution you'd like**
Import whole (+nested) folders & have FOLDERS in the app to categorize my photos just as they are in my files.

**Describe alternatives you've considered**
no

**Additional context**
no

Thanks.

**Comment by ralaud** [comment]
Related to #41

**Comment by leonlatsch** [comment]
Yes so collections are already planned for the next major release and will be implemented once videos are finished.
So, nedted folders may get complicated, but importing a folder as a collection is a good idea.

**Comment by leonlatsch** [comment]
I think the best way is to add a option to the collections feature, to directly import elements into a collection.
Is this a suitable solution for you @fourteen-1?

**Comment by leonlatsch** [comment]
So, Importing whole folders is possible atm. Importing nested folders will not be done, but a direct import into a collection will be implementedwith #41.
So this will be closed.
